// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {db} from '../models';
import {gp} from '../models';

export function CheckUpdate():Promise<string>;

export function FetchSimInfo(arg1:string):Promise<main.SimInfo>;

export function GetGpPath():Promise<string>;

export function InstallApplet(arg1:string,arg2:db.Key,arg3:string,arg4:string):Promise<gp.Result>;

export function ListApplets(arg1:string,arg2:db.Key):Promise<Array<gp.ListResult>>;

export function ListCardReader():Promise<Array<string>>;

export function SaveSimConfig(arg1:string,arg2:db.Sim):Promise<boolean>;

export function SelectCapFilePath():Promise<string>;

export function ShowConfirmDialog(arg1:string,arg2:string):Promise<string>;

export function ShowErrorDialog(arg1:string,arg2:string):Promise<void>;

export function UninstallApplet(arg1:string,arg2:db.Key,arg3:string):Promise<gp.Result>;
