// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function FetchSimInfo(arg1) {
  return window['go']['main']['App']['FetchSimInfo'](arg1);
}

export function GetGpPath() {
  return window['go']['main']['App']['GetGpPath']();
}

export function InstallApplet(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InstallApplet'](arg1, arg2, arg3, arg4);
}

export function ListApplets(arg1, arg2) {
  return window['go']['main']['App']['ListApplets'](arg1, arg2);
}

export function ListCardReader() {
  return window['go']['main']['App']['ListCardReader']();
}

export function SaveSimConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveSimConfig'](arg1, arg2);
}

export function SelectCapFilePath() {
  return window['go']['main']['App']['SelectCapFilePath']();
}

export function ShowConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowConfirmDialog'](arg1, arg2);
}

export function ShowErrorDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowErrorDialog'](arg1, arg2);
}

export function UninstallApplet(arg1, arg2, arg3) {
  return window['go']['main']['App']['UninstallApplet'](arg1, arg2, arg3);
}
