name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}

jobs:
  package:
    strategy:
      matrix:
        # platform: [windows-latest, macos-latest]
        platform: [macos-latest]
        go-version: [1.21]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      # wails.jsonでフロントエンドのビルドおよびインストールコマンドを設定していない場合、ここで手動でフロントエンドをビルドする必要があるかもしれません。
      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Build Wails app
        run: |
          wails build
      - name: Notarize Release Build
        uses: lando/notarize-action@v2
        with:
          product-path: "./build/bin/app.app"
          appstore-connect-username: ${{ secrets.APPLE_USERNAME }}
          appstore-connect-password: ${{ secrets.APPLE_PASSWORD }}
          appstore-connect-team-id: ${{ secrets.APPLE_TEAM_ID }}
          primary-bundle-id: dev.mohemohe.ent.com.common-creation.sim-applet-manager
      - name: "Staple Release Build"
        uses: BoundfoxStudios/action-xcode-staple@v1
        with:
          product-path: "./build/bin/app.app"
      - name: upload artifacts macOS
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: sim-applet-manager-macos
          path: build/bin/*
      - name: upload artifacts windows
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: sim-applet-manager-windows
          path: build/bin/*
